// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjetintmeeusqritoxdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZXRpbnRtZWV1c3FyaXRveGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDczNzcsImV4cCI6MjA3NjgyMzM3N30.Bc-UxdjofFVAToR3_yu8SfJL_f4lVEnI6kmGXDYa0HU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});